CREATE TABLE identifications (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id BIGINT NOT NULL,
    --plant_id can be NULL because a plant can be "UNKNOWN" sometimes
                                 plant_id BIGINT,
                                 status VARCHAR(50) NOT NULL,
    --confidence can be NULL because, there'sno confidence when status is "processing"
                                 confidence NUMERIC(5,4),
                                 model_version VARCHAR(100),
                                 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_identifications_user
                                     FOREIGN KEY (user_id)
                                         REFERENCES users(id),

                                 CONSTRAINT fk_identifications_plant
                                     FOREIGN KEY (plant_id)
                                         REFERENCES plants(id),

                                 CONSTRAINT chk_identifications_status
                                     CHECK (
                                         status IN (
                                                    'SUCCESS',
                                                    'LOW_CONFIDENCE',
                                                    'UNKNOWN',
                                                    'REJECTED',
                                                    'PROCESSING',
                                                    'FAILED'
                                             )
                                         ),

                                 CONSTRAINT chk_identifications_confidence
                                     CHECK (
                                         confidence IS NULL
                                             OR (confidence >= 0 AND confidence <= 1)
                                         )
);