CREATE TABLE identification_images (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       identification_id BIGINT NOT NULL,
                                       image_reference TEXT NOT NULL,
                                       plant_part VARCHAR(50),
                                       sequence_number INTEGER NOT NULL,
                                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT fk_identification_images_identification
                                           FOREIGN KEY (identification_id)
                                               REFERENCES identifications(id)
                                               --if identification is deleted then its identifiaction images should be deletd as well
                                               ON DELETE CASCADE,

                                       CONSTRAINT chk_identification_images_sequence
                                           CHECK (sequence_number > 0)
);